name: Deploy HelloCloudAspx to Azure

on:
  push:
    branches:
      - HelloAspx  # adapte ici si ta branche s'appelle autrement

permissions:
  id-token: write
  contents: read

jobs:
  build-and-deploy:
    runs-on: windows-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}
      ARM_USE_OIDC: true

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v1.3.1

      - name: Restore NuGet packages
        run: nuget restore HelloCloudAspx.sln

      - name: Build and publish (Web Forms)
        working-directory: ./HelloCloudAspx
        run: msbuild HelloCloudAspx.csproj /p:Configuration=Release /p:DeployOnBuild=true /p:PublishProfile=FolderProfile

      - name: Show publish folder content for debug
        working-directory: ./HelloCloudAspx
        run: dir publish

      - name: Compress published folder
        working-directory: ./HelloCloudAspx
        run: Compress-Archive -Path publish\* -DestinationPath published.zip

      - name: Login to Azure
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v2
        with:
          app-name: ${{ secrets.AZURE_APP_SERVICE_NAME }}
          package: published.zip
